# Generated by Selenium IDE
import pytest
import allure
from selenium import webdriver
from selenium.webdriver.common.by import By
from base.base_test import BaseTest

class TestDefaultSuite(BaseTest):

    vars = {}
    def test_first_scenario(self):
        self.sbis_home_page.open()
        self.sbis_home_page.click_to_contacts_link()
        # self.sbis_contacts_page.is_opened()
        # self.vars["sbis"] = self.driver.current_window_handle
        self.sbis_contacts_page.click_to_tenzor_banner()
        # self.vars["tenzor"] = self.wait_for_window(2000)
        # self.driver.switch_to.window(self.vars["tenzor"])
        self.tenzor_home_page.is_opened()

        # self.login_page.enter_login(self.data.LOGIN)
        # self.login_page.enter_password(self.data.PASSWORD)
        # self.login_page.click_submit_button()
        # self.dashboard_page.is_opened()
        # self.dashboard_page.click_my_info_link()
        # self.personal_page.is_opened()
        # self.personal_page.change_name(f"Test {random.randint(1, 100)}")
        # self.personal_page.save_changes()
        # self.personal_page.is_changes_saved()
        # self.personal_page.make_screenshot("Success")


    # self.vars["window_handles"] = self.driver.window_handles
    # self.driver.find_element(By.CSS_SELECTOR, ".sbisru-Contacts__border-left--border-xm img").click()
    # self.vars["win8331"] = self.wait_for_window(2000)
    # self.vars["root"] = self.driver.current_window_handle
    # self.driver.switch_to.window(self.vars["win8331"])
    # self.driver.execute_script("window.scrollTo(0,0)")
    # self.driver.find_element(By.CSS_SELECTOR, ".tensor_ru-Index__block4-content .tensor_ru-link").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".s-Grid-col:nth-child(1) .tensor_ru-About__block3-image-filter").click()
    # self.driver.execute_script("window.scrollTo(0,0)")
    # self.driver.execute_script("window.scrollTo(0,0)")
    # self.driver.execute_script("window.scrollTo(0,0)")
    # self.driver.find_element(By.CSS_SELECTOR, ".tensor_ru-Index__block4-content > .tensor_ru-Index__card-title").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".tensor_ru-Index__block4-content > .tensor_ru-Index__card-title").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".tensor_ru-Index__block4-content > .tensor_ru-Index__card-title").click()
    # element = self.driver.find_element(By.CSS_SELECTOR, ".tensor_ru-Index__block4-content > .tensor_ru-Index__card-title")
    # actions = ActionChains(self.driver)
    # actions.double_click(element).perform()
    # self.driver.find_element(By.CSS_SELECTOR, ".tensor_ru-Index__block4-content").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".tensor_ru-Index__block4-content").click()
    # self.driver.switch_to.window(self.vars["root"])
